/* 2- Return number of employees registered for each location. */

WITH EMP_COUNT AS
    (SELECT EMP.LOCATION_ID, COUNT(EMP.EMPLOYEE_ID) EMPLOYEE_COUNT
    FROM HR_EMPLOYEES EMP
    JOIN HR_LOCATIONS LOC
    ON LOC.LOCATION_ID = EMP.LOCATION_ID
    GROUP BY EMP.LOCATION_ID)
SELECT LOC.LOCATION_ID, LOC.LOCATION_NAME, EMP_COUNT.EMPLOYEE_COUNT
FROM HR_LOCATIONS LOC
JOIN EMP_COUNT ON EMP_COUNT.LOCATION_ID = LOC.LOCATION_ID
ORDER BY LOCATION_ID