/* 5- Return reverse of those department names. (For example => input='Benefits', output = 'stifeneB'). */

CREATE FUNCTION STR_REVERSE (LEN IN NUMBER, WORDS IN VARCHAR2)
    RETURN VARCHAR2 
    IS 
    x number(3);
    s VARCHAR2(50);

    BEGIN
        FOR x IN 1 .. LEN LOOP
            s := s || SUBSTR(WORDS, x*-1, 1);
        END LOOP;
        
        RETURN s;
    END; 


SELECT DEPARTMENT_ID, DEPARTMENT_NAME, STR_REVERSE(LENGTH(DEPARTMENT_NAME), DEPARTMENT_NAME) REVERSED_NAME
FROM HR_DEPARTMENTS
MINUS
SELECT EMP.DEPARTMENT_ID, DEP.DEPARTMENT_NAME, STR_REVERSE(LENGTH(DEP.DEPARTMENT_NAME), DEP.DEPARTMENT_NAME) REVERSED_NAME
FROM HR_EMPLOYEES EMP
JOIN HR_DEPARTMENTS DEP ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
GROUP BY EMP.DEPARTMENT_ID, DEP.DEPARTMENT_NAME






/* Alternative solution */

SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM HR_DEPARTMENTS
MINUS
SELECT EMP.DEPARTMENT_ID, DEP.DEPARTMENT_NAME
FROM HR_EMPLOYEES EMP
JOIN HR_DEPARTMENTS DEP ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
GROUP BY EMP.DEPARTMENT_ID, DEP.DEPARTMENT_NAME

SELECT LISTAGG(STR) WITHIN GROUP (ORDER BY RN DESC)
FROM
(SELECT ROWNUM RN, SUBSTR(DEPARTMENT_NAME,ROWNUM,1) STR FROM HR_DEPARTMENTS
CONNECT BY LEVEL <= LENGTH(DEPARTMENT_NAME));

SELECT LISTAGG(r) 
         within GROUP ( ORDER BY ROWNUM ) 
FROM   (SELECT substr(DEPARTMENT_NAME, -LEVEL, 1) r 
        FROM   HR_DEPARTMENTS 
        CONNECT BY LEVEL <= Length(DEPARTMENT_NAME)); 