/* 4- Return the string between 1st letter from the end and 3th letter from the end. (For example => input='Benefits', output = 'sti'). */

CREATE FUNCTION STR_REVERSE (LEN IN NUMBER, WORDS IN VARCHAR2)
    RETURN VARCHAR2 
    IS 
    x number(3);
    s VARCHAR2(50);

    BEGIN
        FOR x IN 1 .. LEN LOOP
            s := s || SUBSTR(WORDS, x*-1, 1);
        END LOOP;
        
        RETURN s;
    END; 

SELECT DEPARTMENT_ID, DEPARTMENT_NAME, STR_REVERSE(3, SUBSTR(DEPARTMENT_NAME, -3)) REVERSED_THREE_LETTER
FROM HR_DEPARTMENTS
MINUS
SELECT EMP.DEPARTMENT_ID, DEP.DEPARTMENT_NAME, STR_REVERSE(3, SUBSTR(DEP.DEPARTMENT_NAME, -3)) REVERSED_THREE_LETTER
FROM HR_EMPLOYEES EMP
JOIN HR_DEPARTMENTS DEP ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
GROUP BY EMP.DEPARTMENT_ID, DEP.DEPARTMENT_NAME


/* Alternative solution */
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, SUBSTR(REVERSE(DEPARTMENT_NAME),1,3) REVERSED_THREE_LETTER
FROM HR_DEPARTMENTS
MINUS
SELECT EMP.DEPARTMENT_ID, DEP.DEPARTMENT_NAME,  SUBSTR(REVERSE(DEPARTMENT_NAME),1,3) REVERSED_THREE_LETTER
FROM HR_EMPLOYEES EMP
JOIN HR_DEPARTMENTS DEP ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
GROUP BY EMP.DEPARTMENT_ID, DEP.DEPARTMENT_NAME