/* 3- some departments don't have any registered employee record. Return 5th letter of those department names. */

SELECT DEPARTMENT_ID, DEPARTMENT_NAME, SUBSTR(DEPARTMENT_NAME, 5, 1) FIFTH_LETTER
FROM HR_DEPARTMENTS
MINUS
SELECT EMP.DEPARTMENT_ID, DEP.DEPARTMENT_NAME, SUBSTR(DEP.DEPARTMENT_NAME, 5, 1) FIFTH_LETTER
FROM HR_EMPLOYEES EMP
JOIN HR_DEPARTMENTS DEP ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
GROUP BY EMP.DEPARTMENT_ID, DEP.DEPARTMENT_NAME