create table HR_DEPARTMENTS (
	department_id NUMBER,
	department_name VARCHAR2(50),
	location_id NUMBER
);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (1, 'Accounting', 16);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (2, 'Human Resources', 19);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (3, 'Human Resources', 20);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (4, 'Engineering', 20);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (5, 'Training', 13);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (6, 'Sales', 6);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (7, 'Business Development', 4);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (8, 'Product Management', 20);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (9, 'Legal', 7);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (10, 'Marketing', 19);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (11, 'Marketing', 3);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (12, 'Human Resources', 11);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (13, 'Engineering', 18);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (14, 'Legal', 3);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (15, 'Training', 16);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (16, 'Legal', 1);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (17, 'Support', 14);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (18, 'Engineering', 10);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (19, 'Legal', 14);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (20, 'Business Development', 7);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (21, 'Support', 17);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (22, 'Research and Development', 5);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (23, 'Engineering', 13);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (24, 'Accounting', 17);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (25, 'Research and Development', 14);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (26, 'Research and Development', 12);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (27, 'Sales', 1);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (28, 'Sales', 10);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (29, 'Support', 11);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (30, 'Accounting', 18);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (31, 'Engineering', 6);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (32, 'Services', 19);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (33, 'Product Management', 11);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (34, 'Research and Development', 15);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (35, 'Legal', 3);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (36, 'Engineering', 19);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (37, 'Business Development', 5);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (38, 'Accounting', 20);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (39, 'Product Management', 15);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (40, 'Sales', 4);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (41, 'Product Management', 2);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (42, 'Human Resources', 14);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (43, 'Engineering', 14);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (44, 'Product Management', 19);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (45, 'Legal', 3);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (46, 'Support', 3);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (47, 'Business Development', 11);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (48, 'Legal', 17);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (49, 'Human Resources', 14);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (50, 'Engineering', 18);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (51, 'Sales', 2);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (52, 'Training', 7);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (53, 'Marketing', 16);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (54, 'Research and Development', 12);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (55, 'Legal', 11);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (56, 'Business Development', 6);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (57, 'Research and Development', 9);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (58, 'Marketing', 5);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (59, 'Sales', 14);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (60, 'Engineering', 14);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (61, 'Human Resources', 8);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (62, 'Product Management', 6);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (63, 'Human Resources', 4);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (64, 'Business Development', 7);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (65, 'Business Development', 6);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (66, 'Human Resources', 2);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (67, 'Research and Development', 4);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (68, 'Legal', 20);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (69, 'Services', 20);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (70, 'Research and Development', 7);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (71, 'Research and Development', 16);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (72, 'Support', 6);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (73, 'Sales', 14);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (74, 'Research and Development', 18);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (75, 'Training', 19);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (76, 'Legal', 8);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (77, 'Training', 20);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (78, 'Legal', 8);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (79, 'Marketing', 3);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (80, 'Training', 17);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (81, 'Marketing', 14);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (82, 'Marketing', 10);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (83, 'Sales', 5);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (84, 'Marketing', 12);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (85, 'Legal', 16);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (86, 'Accounting', 16);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (87, 'Sales', 15);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (88, 'Accounting', 16);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (89, 'Accounting', 12);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (90, 'Accounting', 9);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (91, 'Marketing', 1);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (92, 'Training', 5);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (93, 'Training', 12);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (94, 'Training', 20);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (95, 'Engineering', 19);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (96, 'Research and Development', 8);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (97, 'Engineering', 11);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (98, 'Legal', 16);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (99, 'Product Management', 3);
insert into HR_DEPARTMENTS (department_id, department_name, location_id) values (100, 'Services', 3);
